modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="dragon_block_c_kai"
version="0.0.1"
displayName="Dragon Block C Kai"
displayURL="https://mcreator.net"
credits="Credits to Jin and his brother Ben for the original mod."
authors="Ari Akkre"
description="Remake of the Dragon Block C Mod By a tired nerd fueled by tea and boredom"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.dragon_block_c_kai]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration